# Generated by Django 5.2.8 on 2025-11-16 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField(unique=True)),
                ('date', models.DateField()),
                ('n1', models.PositiveIntegerField()),
                ('n2', models.PositiveIntegerField()),
                ('n3', models.PositiveIntegerField()),
                ('n4', models.PositiveIntegerField()),
                ('n5', models.PositiveIntegerField()),
                ('n6', models.PositiveIntegerField()),
                ('bonus', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('manual', '수동'), ('auto', '자동')], max_length=10)),
                ('n1', models.PositiveIntegerField()),
                ('n2', models.PositiveIntegerField()),
                ('n3', models.PositiveIntegerField()),
                ('n4', models.PositiveIntegerField()),
                ('n5', models.PositiveIntegerField()),
                ('n6', models.PositiveIntegerField()),
                ('bought_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.draw')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
